name: GeminiNPC
main: org.pale.gemininpc.Plugin
version: 0.0.2
api-version: 1.18
depend: [Citizens]

commands:
  gemini:
    description: Gemini NPC config command
    aliases: [gemini]
    usage: /gemini
    permission: gemini
